POST / HTTP/1.1
Content-Type : application/json;charset=UTF-8
Host : amzn1.ask.skill.b74b8d6c-1348-408e-8895-b1b1a208596f
Content-Length :
Accept : application/json
Accept-Charset : utf-8
Signature: 
SignatureCertChainUrl: https://s3.amazonaws.com/echo.api/echo-api-cert.pem

{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.b74b8d6c-1348-408e-8895-b1b1a208596f",
    "application": {
      "applicationId": "amzn1.ask.skill.b74b8d6c-1348-408e-8895-b1b1a208596f"
    },
    "attributes": {
      "key": "string value"
    },
    "user": {
      "userId": "amzn1.ask.account.b74b8d6c-1348-408e-8895-b1b1a208596f",
      "accessToken": "Atza|AAAAAAAA...",
      "permissions": {
        "consentToken": "ZZZZZZZ..."
      }
    }
  },
  "context": {
    "System": {
      "device": {
        "deviceId": "string",
        "supportedInterfaces": {
          "AudioPlayer": {}
        },
        "persistentEndpointId" : "amzn1.alexa.endpoint.b74b8d6c-1348-408e-8895-b1b1a208596f"    
      },
      "application": {
        "applicationId": "amzn1.ask.skill.b74b8d6c-1348-408e-8895-b1b1a208596f"
      },
      "user": {
        "userId": "amzn1.ask.account.b74b8d6c-1348-408e-8895-b1b1a208596f",
        "accessToken": "Atza|AAAAAAAA...",
        "permissions": {
          "consentToken": "ZZZZZZZ..."
        }
      },
      "person": {
        "personId": "amzn1.ask.person.b74b8d6c-1348-408e-8895-b1b1a208596f",
        "accessToken": "Atza|BBBBBBB..."
      },
      "unit": {
        "unitId": "amzn1.ask.unit.b74b8d6c-1348-408e-8895-b1b1a208596f",
        "persistentUnitId" : "amzn1.alexa.unit.did.[unique-value-here]"
      },
      "apiEndpoint": "https://api.amazonalexa.com",
      "apiAccessToken": "AxThk..."
    },
    "AudioPlayer": {
      "playerActivity": "PLAYING",
      "token": "audioplayer-token",
      "offsetInMilliseconds": 0
    }
  },
  "request": {}
}